export const courseYear11 = [
  {
    header: ['S/N', 'Course Code', 'Course Title', 'L', 'P', 'CU', 'CH'],
    rows: [
      {
        SN: '1',
        'Course Code': 'COM 111',
        'Course Title': 'Introduction to computing',
        L: '2',
        P: '2',
        CU: '3',
        CH: '4',
      },
      {
        SN: '2',
        'Course Code': 'COM 112',
        'Course Title': 'Introduction to Digital Electronics',
        L: '2',
        P: '2',
        CU: '3',
        CH: '4',
      },
      {
        SN: '3',
        'Course Code': 'COM 113',
        'Course Title': 'Introduction to Programming',
        L: '2',
        P: '2',
        CU: '4',
        CH: '4',
      },
      {
        SN: '4',
        'Course Code': 'COM 114',
        'Course Title': 'Statistics for Computing 1',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '5',
        'Course Code': 'COM 115',
        'Course Title': 'Computer application packages I',
        L: '2',
        P: '2',
        CU: '3',
        CH: '4',
      },
      {
        SN: '6',
        'Course Code': 'MTH 111',
        'Course Title': 'Logic and Linear Algebra',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '7',
        'Course Code': 'GNS 101',
        'Course Title': 'Use of English I',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '8',
        'Course Code': 'GNS 127',
        'Course Title': 'Citizenship Education I',
        L: '2',
        P: '2',
        CU: '4',
        CH: '4',
      },
      {
        SN: '9',
        'Course Code': 'BPH 121',
        'Course Title': 'Optics, waves, Electricity and Magnetism',
        L: '2',
        P: '2',
        CU: '2',
        CH: '2',
      },
      {
        SN: '10',
        'Course Code': 'EEP 127',
        'Course Title': 'Skill Acquisition ',
        L: '',
        P: '3',
        CU: '1',
        CH: '3',
      },
      {
        SN: '',
        'Course Code': '',
        'Course Title': '',
        L: '',
        P: '',
        CU: '26',
        CH: '',
      },
    ],
  },
];

export const courseYear12 = [
  {
    header: ['S/N', 'Course Code', 'Course Title', 'L', 'P', 'CU', 'CH'],
    rows: [
      {
        SN: '1',
        'Course Code': 'COM 121',
        'Course Title': 'Programming using C Language',
        L: '2',
        P: '2',
        CU: '3',
        CH: '4',
      },
      {
        SN: '2',
        'Course Code': 'COM 122',
        'Course Title': 'Introduction to Internet',
        L: '1',
        P: '2',
        CU: '3',
        CH: '3',
      },
      {
        SN: '3',
        'Course Code': 'COM 123',
        'Course Title': 'Programming Language using Java I',
        L: '2',
        P: '2',
        CU: '3',
        CH: '4',
      },
      {
        SN: '4',
        'Course Code': 'COM 124',
        'Course Title': 'Data structure and Algorithms',
        L: '2',
        P: '1',
        CU: '3',
        CH: '3',
      },
      {
        SN: '5',
        'Course Code': 'COM 125',
        'Course Title': 'Introduction to Systems Analysis and Design',
        L: '2',
        P: '1',
        CU: '3',
        CH: '3',
      },
      {
        SN: '6',
        'Course Code': 'COM 126',
        'Course Title': 'PC Upgrade & Maintenance',
        L: '1',
        P: '3',
        CU: '3',
        CH: '4',
      },
      {
        SN: '7',
        'Course Code': 'GNS 128',
        'Course Title': 'Citizenship Education II',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '8',
        'Course Code': 'GNS 102',
        'Course Title': 'Communication in English',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '9',
        'Course Code': 'EED 126',
        'Course Title': 'Practice of Entrepreneurship',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '10',
        'Course Code': 'GNS 228',
        'Course Title': 'Research Methods',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '11',
        'Course Code': 'MTH 121',
        'Course Title': 'Calculus I',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '',
        'Course Code': '',
        'Course Title': '',
        L: '',
        P: '',
        CU: '28',
        CH: '',
      },
    ],
  },
];

export const courseYear21 = [
  {
    header: ['S/N', 'Course Code', 'Course Title', 'L', 'P', 'CU', 'CH'],
    rows: [
      {
        SN: '1',
        'Course Code': 'COM 211',
        'Course Title': 'Programming using Java II',
        L: '2',
        P: '2',
        CU: '4',
        CH: '4',
      },
      {
        SN: '2',
        'Course Code': 'COM 212',
        'Course Title': 'Introduction to systems Programming',
        L: '1',
        P: '1',
        CU: '2',
        CH: '2',
      },
      {
        SN: '3',
        'Course Code': 'COM 213',
        'Course Title': 'Unified Modelling Language (UML)',
        L: '2',
        P: '2',
        CU: '3',
        CH: '4',
      },
      {
        SN: '4',
        'Course Code': 'COM 214',
        'Course Title': 'Computer Systems Troubleshooting',
        L: '1',
        P: '2',
        CU: '3',
        CH: '3',
      },
      {
        SN: '5',
        'Course Code': 'COM 215',
        'Course Title': 'Computer Application Packages II',
        L: '2',
        P: '2',
        CU: '3',
        CH: '4',
      },
      {
        SN: '6',
        'Course Code': 'COM 216',
        'Course Title': 'Statistics for Computing II',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '7',
        'Course Code': 'SIWES',
        'Course Title': 'Citizenship Education II',
        L: '0',
        P: '4',
        CU: '4',
        CH: '4',
      },
      {
        SN: '8',
        'Course Code': 'GNS 201',
        'Course Title': 'Use of English II',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '9',
        'Course Code': 'EED 216',
        'Course Title': 'Practice of Entrepreneurship',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '10',
        'Course Code': 'MTH 213',
        'Course Title': 'Linear Algebra',
        L: '2',
        P: '3',
        CU: '2',
        CH: '4',
      },

      {
        SN: '',
        'Course Code': '',
        'Course Title': '',
        L: '',
        P: '',
        CU: '27',
        CH: '',
      },
    ],
  },
];

export const courseYear22 = [
  {
    header: ['S/N', 'Course Code', 'Course Title', 'L', 'P', 'CU', 'CH'],
    rows: [
      {
        SN: '1',
        'Course Code': 'COM 221',
        'Course Title': 'Basic Computer Networking',
        L: '1',
        P: '3',
        CU: '3',
        CH: '4',
      },
      {
        SN: '2',
        'Course Code': 'COM 222',
        'Course Title': 'Seminar on Computer and Society',
        L: '2',
        P: '-',
        CU: '2',
        CH: '2',
      },
      {
        SN: '3',
        'Course Code': 'COM 223',
        'Course Title': 'Basic Hardware Maintenance',
        L: '1',
        P: '2',
        CU: '2',
        CH: '3',
      },
      {
        SN: '4',
        'Course Code': 'COM 224',
        'Course Title': 'Management Information system',
        L: '2',
        P: '1',
        CU: '2',
        CH: '3',
      },
      {
        SN: '5',
        'Course Code': 'COM 225',
        'Course Title': 'Web Technology',
        L: '2',
        P: '3',
        CU: '3',
        CH: '5',
      },
      {
        SN: '6',
        'Course Code': 'COM 226',
        'Course Title': 'File Organisation and Management',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '7',
        'Course Code': 'GNS 204',
        'Course Title': 'Communication in English II',
        L: '0',
        P: '4',
        CU: '4',
        CH: '4',
      },
      {
        SN: '8',
        'Course Code': 'COM 227',
        'Course Title': 'Project',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '9',
        'Course Code': 'MTH 221',
        'Course Title': 'Mathematical Methods I',
        L: '2',
        P: '0',
        CU: '2',
        CH: '2',
      },
      {
        SN: '',
        'Course Code': '',
        'Course Title': '',
        L: '',
        P: '',
        CU: '22',
        CH: '',
      },
    ],
  },
];
